### ISSUE TITLE
SW4-SMD-5.2X5.2X1.5MM pad placement and size is different than specification

### ISSUE THREAD

**Issue by autotel** [Seeed-Studio/OPL_Kicad_Library#3]
The datasheet recommended footprint is different from the footprint in seed OPL. I have made a version according to this recommendation, that I can share.

**Comment by CourageGuo** [comment]
Hi Autotel

Could you tell me more information about footprint? Our engineer said it is the same from datasheet.
![image](https://user-images.githubusercontent.com/29766927/27669909-0a5330c0-5cbc-11e7-8a29-6322dd54399e.png)
![image](https://user-images.githubusercontent.com/29766927/27669911-0d1878c4-5cbc-11e7-8687-368149464143.png)

**Comment by autotel** [comment]
I am not an expert, so you should trust better the engineer. But this kind of things happen all the time, that is why I wanted to help pointing it out. 

The guide to the footprints that I used is just at the right of the image you attached. Please carify me if I did it wrong.

![image](https://user-images.githubusercontent.com/15053243/27784821-86dee05a-6016-11e7-8bcd-524c14b9e73a.png)

**Comment by CourageGuo** [comment]
Hi Autotel

Yes it is right.  Please follow the datasheet.

**Comment by mfaccin** [comment]
Hi, I would like to know if @SeeedFusion corrected it.

**Comment by autotel** [comment]
I don't actually know; probably. Anyways it is always good to measure them
in comparison to the data sheet. Can you confirm yourself?
