### ISSUE TITLE
Connector library not recognized by Kicad

### ISSUE THREAD

**Issue by kevinl95** [Seeed-Studio/OPL_Kicad_Library#4]
`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-6H7AGx-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5PPb8H-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-6H7AGx-build/`

**Comment by kevinl95** [comment]
This is for the alpha version by the way on Mac OS Sierra 10.12.6. The 2016 library file works fine.

**Comment by royassas** [comment]
Same problem here...
