### ISSUE TITLE
Unzip the zips!

### ISSUE THREAD

**Issue by kasbah** [Seeed-Studio/OPL_Kicad_Library#5]
Hey, the way it is it's unnecessarily hard to add these to KiCad.  If you unzipped the zips and added all the files to git that would be way better. It would also allow me to add them to my collection as requested in https://github.com/monostable/kicad_footprints/issues/8.

**Comment by kasbah** [comment]
It seems there is now a fork at https://github.com/imrehg/kicalopl

**Comment by SeeedFusion** [comment]
The new OPLs are now unzipped, thank you!
