### ISSUE TITLE
Footprint conflict

### ISSUE THREAD

**Issue by Kiogora** [Seeed-Studio/OPL_Kicad_Library#6]
Hi,

In the Seeed kicad footprint for MICRO USB - 10118193-0001LF from amphenol, the drill holes are smaller than the USB legs according to the STEP file from amphenol.

Kindly confirm.
![image](https://user-images.githubusercontent.com/23386986/33236154-9eb94f14-d25b-11e7-93d0-06fa5657de7c.png)

**Comment by Huangw0107** [comment]
Updated，thank you
